Improve job validation error messages (#4224) (#4942)
Our job spec verification sometimes return pretty cryptic error messages
to the user. This is a quick fix to make some of those messages more
readable.

Ideally we should plan a long-term solution for this. Maybe introduce a
JSON schema for Job Spec and use one of the existing schema validators.

Additionally, we can look into job spec validation on client side and
fail early if given yaml/json is invalid. We won't be able to check
every rule (some require compute node info, like supported
engines/hardware) but we can totally verify that the job satisfies the
schema. For example
https://github.com/bacalhau-project/bacalhau/issues/4224 is a schema
error so can be caught before even sending any requests to the
orchestrator.



### Before
```
Error: the job provided is invalid: task Task1 validation failed: artifact validation failed: missing artifact target
```

### After
```
Error: the job provided is invalid: task Task1 validation failed: invalid input sources: input source is missing a target
```


Addresses https://github.com/bacalhau-project/bacalhau/issues/4224

<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->

## Summary by CodeRabbit

- **Bug Fixes**
- Improved validation error messages for input sources and tasks to be
more specific and consistent.
- **Tests**
  - Added a new test case for missing input source targets.
  - Updated existing test cases to match revised error messages.

<!-- end of auto-generated comment: release notes by coderabbit.ai -->

Co-authored-by: oleg_k <olgk.work@proton.me>