fix: keep legacy repo verison for backwards compatibility (#4493)
- closes #4428
- closes #4473

New error message when 1.4 opens a 1.5 repo:
```shell
$ bacalhau serve --node-type=compute,requester
Error: failed to reconcile repo: 
Unsupported repository version 4.
Bacalhau does not know how to read this configuration format and
you will need to upgrade to a newer version to upgrade this repository.
```

Co-authored-by: frrist <forrest@expanso.io>
Co-authored-by: Walid Baruni <wdbaruni@gmail.com>