fix: stop jobs with short ids (#4657)
This PR enables stopping jobs using short IDs, such as `j-d43c044b`
instead of `j-d43c044b-f731-4256-a3d6-e62fac426d15`. It also improves
the error reported when passing wrong jobID or if multiple jobs match
the pefix

### Testing Done
- Introduced new `StopSuite` test suite
- Manual testing as shown below
```
# short job id
→ bacalhau job stop j-3dc57b6a
Checking job status

	Connecting to network  ................  done ✅  0.0s
	  Verifying job state  ................  done ✅  0.0s
	         Stopping job  ................  done ✅  0.0s

Job stop successfully submitted with evaluation ID: 65035d30-b093-4458-bd8e-ac5b5aad27a4


# multiple jobs matching the prefix
→ bacalhau job stop j-
Checking job status

	Connecting to network  ................  done ✅  0.0s
	  Verifying job state  ................  err  ❌  0.0s

Error: multiple jobs found for id j-
Hint:  Use full job ID


# no matching job id
→ bacalhau job stop j-123
Checking job status

	Connecting to network  ................  done ✅  0.0s
	  Verifying job state  ................  err  ❌  0.0s

Error: job not found: j-123

```

Fixes #4643 
Fixes #3674 
Fixes #4644