fix: errors and config validation (#4563)
- closes #4539
```shell
$ bacalhau serve --orchestrator  -c orchestrator.port 2222 -c api.port=3333

Error: invalid argument "orchestrator.port" for "-c, --config" flag: config flag key "orchestrator.port" requires a value
```
- closes #4547
```shell
$ bacalhau serve --orchestrator -c config.yaml -c api.host=1.1.1.1 --api-host 3.3.3.3

Error: flag: --api-host and config flag key "api.host" cannot both be provided. Only one may be used
Hint:  Remove --api-host or --confg/-c api.host=1.1.1.1 from the command
```
- closes #4546
```shell
$ bacalhau config set --help
The 'set' command allows you to modify configuration values in your Bacalhau configuration file.

This command supports two input formats for setting configuration values:

 Key=Value Format:
   Alternatively, you can pass the key and value together in a single argument using the 'key=value' format.
   Example:
     bacalhau config set api.host=127.0.0.1
     bacalhau config set compute.orchestrators=http://127.0.0.1:1234,http://1.1.1.1:1234
     bacalhau config set compute.labels=foo=bar,baz=buz

Usage:
  ./bin/linux/amd64/bacalhau config set [flags]

Flags:
  -c, --config string   Path to the config file (default is $BACALHAU_DIR/config.yaml)
  -h, --help            help for set

Global Flags:
      --api-host string   The host for the client and server to communicate on (via REST).
                          Ignored if BACALHAU_API_HOST environment variable is set. (default "0.0.0.0")
      --api-port int      The port for the client and server to communicate on (via REST).
                          Ignored if BACALHAU_API_PORT environment variable is set. (default 1234)
      --data-dir string   The filesystem path bacalhau inits or opens a repo in (default "/home/frrist/.bacalhau")
```

---------

Co-authored-by: frrist <forrest@expanso.io>
Co-authored-by: Walid Baruni <wdbaruni@gmail.com>