Structured events in place of comment strings (#3771)
This PR implements the structure proposed in [Improve Error
Reporting](https://www.notion.so/expanso/Improve-Error-Reporting-c19f5516822b47de980d76ff43ff4bbe)
as a first step towards providing richer progress reporting during job
execution.

The "tl;dr;" is that we will move to using an event stream for reporting
progress on jobs. The event stream will help users understand the
progress of their job and give them extra context about any failures
that occur. This will allow us to show a richer view in the UI, e.g. the
user will be able to see "downloading Docker image" instead of just "job
running".

To achieve this vision, we need to build this infrastructure for
generating events, recording them in the job history, and displaying
them (done), replace the orchestrator/compute callbacks mechanism (later
PR), and then give lower level components the ability to push events
(later PR).

This PR also includes some facility for structured error reporting. This
allows low-level components to throw structured errors that provide a
richer event than the ones generated automatically. This is used in e.g.
the ErrNotEnoughNodes case and docker ImageUnavailable case so far.

This gives us the ability to output hints as part of our messages back
to the user:


![carbon](https://github.com/bacalhau-project/bacalhau/assets/4951176/04e63f09-4f7e-44ed-883a-85fb4b9a7f2d)

The output of `describe` now shows a split history between the overall
job and its executions:
```
% ./bin/darwin/arm64/bacalhau job describe j-66081fef-8dd2-48de-9997-bbe23a62f0be

ID            = j-66081fef-8dd2-48de-9997-bbe23a62f0be
Name          = Docker Job
Namespace     = default
Type          = batch
State         = Completed
Count         = 1
Created Time  = 2024-04-10 06:56:26
Modified Time = 2024-04-10 06:56:29
Version       = 0

Summary
Completed = 1

Job History
 TIME       REV.  STATE      TOPIC       EVENT          DETAILS 
 0s         1     Pending    Submission  Job submitted          
 2.618376s  2     Running                                       
 2.840423s  3     Completed                                     

Executions
 ID          NODE ID     STATE      DESIRED  REV.  CREATED  MODIFIED  COMMENT      
 e-5886e01f  n-ffc3e455  Completed  Stopped  6     8s ago   5s ago    Accepted job 

Execution e-5886e01f History
 TIME       REV.  STATE              TOPIC            EVENT         DETAILS               
 0s         1     New                                                                     
 8.165ms    2     AskForBid                                                               
 2.569966s  3     AskForBidAccepted  Requesting node  Accepted job  FailsExecution: false 
                                                                    IsError: false        
                                                                    Retryable: false      
 2.590902s  4     AskForBidAccepted                                                       
 2.613668s  5     BidAccepted                                                             
 2.803923s  6     Completed                                                               

Standard Output
15
```

Resolves
https://github.com/bacalhau-project/expanso-planning/issues/693.
Resolves
https://github.com/bacalhau-project/expanso-planning/issues/694.

### TODO in this PR
- [x] Add more documentation
- [x] Sort execution histories by time DESC so that most relevant
execution is first
- [x] Do some more examples of using structured errors from compute node
components

---------

Co-authored-by: Ross Jones <ross@register-dynamics.co.uk>
Co-authored-by: Walid Baruni <wdbaruni@gmail.com>